In [1]:
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Regression Practice"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Read in and explore the data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.linear_model import LinearRegression\n",
    "import pandas as pd\n",
    "import seaborn as sns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Read in the two data sets\n",
    "df_train = pd.read_csv('../train_data.csv')\n",
    "df_test = pd.read_csv('../test_data.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>y</th>\n",
       "      <th>x1</th>\n",
       "      <th>x2</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>737.721966</td>\n",
       "      <td>1994</td>\n",
       "      <td>17</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>372.012721</td>\n",
       "      <td>1987</td>\n",
       "      <td>11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>298.244694</td>\n",
       "      <td>1990</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>353.815829</td>\n",
       "      <td>1991</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>899.943226</td>\n",
       "      <td>1998</td>\n",
       "      <td>15</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "            y    x1  x2\n",
       "0  737.721966  1994  17\n",
       "1  372.012721  1987  11\n",
       "2  298.244694  1990   4\n",
       "3  353.815829  1991   5\n",
       "4  899.943226  1998  15"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_train.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>y</th>\n",
       "      <th>x1</th>\n",
       "      <th>x2</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>585.419191</td>\n",
       "      <td>1997</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>269.365326</td>\n",
       "      <td>1988</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>317.658704</td>\n",
       "      <td>1989</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>400.653320</td>\n",
       "      <td>1986</td>\n",
       "      <td>11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>444.240501</td>\n",
       "      <td>1987</td>\n",
       "      <td>12</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "            y    x1  x2\n",
       "0  585.419191  1997   1\n",
       "1  269.365326  1988   3\n",
       "2  317.658704  1989   4\n",
       "3  400.653320  1986  11\n",
       "4  444.240501  1987  12"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_test.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(140, 3)"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_train.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(60, 3)"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_test.shape"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Create visualizations to explore the data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAWwAAAD8CAYAAABTjp5OAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8vihELAAAACXBIWXMAAAsTAAALEwEAmpwYAAAehklEQVR4nO3dfXRV9Z3v8fc3JwHDo8bIY2jR3vhAa8WnYJdPWEQCdaS11yl4LyrXLmxvWeP0ti6Z6YzoeOderdOZdpa2moEsaHst12l1pEJBypKLHQWDhYYHQQI4JgbBEvCBgJDke//Ihp4cT5Jzck7Oyd75vNbaK2fv32/v/T1n6ef8+J19zjZ3R0RE+r6CfBcgIiKpUWCLiISEAltEJCQU2CIiIaHAFhEJCQW2iEhIKLBFRDphZtVmdtDMtnXSbmb2z2ZWZ2a1ZnZZXFulme0K2hZkox4FtohI55YAlV20TwfKg2Ue8BMAM4sBTwTtE4DZZjYh02IU2CIinXD39UBTF11mAj/1dhuAM81sNFAB1Ln7Xnc/ASwL+makMNMDdOchM32Vspdl/LYt3bom3wX0E6PdLdNjpJM5D8I9tI+MT6ly96o0TjcWqI9bbwi2Jds+KY3jJtXrgS0i0lcF4ZxOQCdK9gbjXWzPiAJbRCIlx/O8DcC4uPUyoBEY0Mn2jGgOW0QipTCNJQuWA3cEV4tcBbzv7vuBGqDczM41swHArKBvRjTCFpFIyeYo1Mx+AUwGSs2sAVgIFAG4+5PASmAGUAc0A3ODthYzmw+sBmJAtbtvz7QeBbaIREo2A9vdZ3fT7sC3OmlbSXugZ40CW0QiJcrzvApsEYkUBbaISEgosEVEQiKW7wJ6kQJbRCJFgS0iEhKaEhERCQkFtohISCiwRURCIsqhFuXnJiL9kEbYIiIhkfEPavdhCmwRiRRd1iciEhKaEhERCQkFtohISEQ51KL83ESkH9IIW0QkJBTYIiIhEeXL+qL8ZiQi/VAsjaU7ZlZpZrvMrM7MFiRpv8/MtgTLNjNrNbOSoO0tM9satG3KxnPTCFtEIiVboWZmMeAJYCrQANSY2XJ333Gqj7s/BjwW9P8z4Nvu3hR3mBvc/Y9ZKkkjbBGJloI0lm5UAHXuvtfdTwDLgJld9J8N/CKD0rulwBaRSMliYI8F6uPWG4Jtn2Bmg4BK4Fdxmx140cxeN7N5aT6NpDQlIiKRks4oNAjS+DCtcveqU81JdvFODvVnwL8nTIdc7e6NZjYCWGNmO919fRrlfYICW0QiJZ3ADsK5qpPmBmBc3HoZ0NhJ31kkTIe4e2Pw96CZPUf7FEtGga0pERGJFEtj6UYNUG5m55rZANpDefknzmc2HLgeeD5u22AzG3rqMXATsC2DpwVohC0iEVOUpeO4e4uZzQdW034VYLW7bzezbwTtTwZdvwK86O5H43YfCTxnZtCes0+7+6pMazL3zqZksuMhs949QRbdsngx5998M0cPHuQnF1+c73JSNiHfBSQYOW0al/7oR1gsxt5Fi9j16KMd2guHDWPSz3/OoE99Ciss5M1/+AfeWrKEgoEDuWH9egoGDsQKC2n45S/Z8eCD+XkSCa7JdwFdGDhtGsN+9COIxWhetIijCa83wIDrr2fYD38IRUW0/fGPNE2enPM6UzHaPePvvdSkkTlXZuF8uaTAjvOpa6/lxEcf8ZWf/lSB3VMFBUx/803WT51Kc0MDN9bUsGH2bD58443TXS78q7+iaPhwti5YwIDSUqbv2sXyUaPwkyeJDR5M69GjWGEhN/zud2y5916aNm7M4xNq12cDu6CAc958k6apU2ltaKC0poYjs2fTEvd62/DhnP3KKzRVVtJWX0/BOefQ9t57eSy6c9kI7NfTyJzLQxbY3c5hm9l8MzsrF8Xk29svv8yxpqbuO0qnSioq+KiujqP79uEnT1K/bBljZyZcuupO4dChABQOGcKJpia8pQWA1qPt/6osKCqioKgIenlAEXZFFRW01tXRum8fnDzJsWXLGJjwehfffjvHn32Wtvr2K9T6alhnSxYv6+tzUql5FO3f8Hkm+JpmqN6RJLeKx46luf5Pl642NzRQPLbjpat1jz/OsIsu4ubGRqZt3crme+/9UzAXFDB182ZuOXiQA2vW0PTaa7ksP3RiY8fSGvd6tzU0EEt4vQvPP5+Cs86i5KWXKN20ieI5c3JdZk7168B2978ByoHFwF3AbjP7X2b2mV6uTUIo2ft54rTbyGnTOLJlCy+MGcOLEydy2eOPnx5x09bGmksv5YWyMkoqKhj22c/mouzwSjZ+SvxXSWEhRZdfzuEvfYlD06Yx5G//llh5eW7qy4N+HdgA3v5/3LvB0gKcBfzSzL6frL+ZzTOzTWa2KSu/eCKh0dzQwKBxf7p0dVBZGccbO166eu7cubzz7LMAHN2zh6P79jH0wgs79Dn5/vu8t24doyore7/oEGttaCAW93oXlJXRmvB6tzY08PGqVXhzM37oECfWr6fokktyXWrOFKaxhE0qc9h/YWavA98H/h242N2/CVwOfDXZPu5e5e5XuPsVV2S1XOnrDtfUMKS8nEHjx2NFRYybNYvG5R0vXW1++21GTJkCwMARIxh6wQUc3buXAaWlFA0fDkDBGWcw4sYb+XDnzpw/hzA5WVNDrLyc2PjxUFRE8axZfJzwen/8/PMMuPZaiMWguJiiSZM6fCgZNVEeYafyJlMK3Oru/xG/0d3bzOzm3ikrP259+mnGT57MoNJSvl1fz7qFC9lcXZ3vskLFW1vZPH8+161ejcVi7Kuu5oMdOzjvnnsA2PvUU+x4+GGuXLKEm2prwYza++/nxKFDDL/4Yq5cuhSLxbCCAuqfeYb9K1bk+Rn1ca2tfDB/PiWrV0MsxrHqalp27GBQ8Ho3P/UULTt38vGqVZTW1kJbG82LFtGyfXueC+89YQziVOmyvgjoU5f1RVSfvawvYrJxWd+eNDLnMyG7rC+M0zgiIp2K8ghbgS0ikRLlUIvycxORfihUcxxpUmCLSKSkcq/GsFJgi0ikaA5bRCQkFNgiIiGhwBYRCYkoh1qUn5uI9EMaYYuIhIQCW0QkJKIc2FF+biLSD2Xz1/qCm7bsMrM6M1uQpH2ymb1vZluC5YFU9+0JjbBFJFKyNQo1sxjwBDAVaKD9zlvL3X1HQteX3f3mHu6bFo2wRSRSsngDgwqgzt33uvsJYBkws5t9srFvpxTYIhIpZpbOcvruWMEyL+5QY4H6uPWGYFuiL5jZH8zsN2Z26p52qe6bFk2JiEi0FKYea37iRBVQ1Ulzst+RSvyt7d8Dn3b3j8xsBvBvtN8DN5V906YRtohES2Fh6kvXGoBxcetlQIcbZrr7B+7+UfB4JVBkZqWp7Nujp5bpAURE+pQ0RtjdqAHKzexc4B1gFnB7fAczGwUccHc3swraB8GHgCPd7dsTCmwRiZYzzsjKYdy9xczmA6tp/9XWanffbmbfCNqfBP4z8E0zawGOAbO8/b6LSffNtCbd0zECdE/H3qd7OuZGNu7pyJgxqWdOY2Oo7negEbaIREv2pkT6nOg+MxHpnxTYIiIhocAWEQkJBbaISEhk6SqRvkiBLSLRohG2iEhIKLBFREJCgS0iEhIKbBGRkFBgi4iEhK4S6Tn9zkXvy+ieQ5KS2zZuzHcJkiqNsEVEQkKBLSISEgpsEZGQUGCLiISEPnQUEQkJjbBFREIiwoGtu6aLSLRk767pmFmlme0yszozW5Ck/b+...

SyntaxError: EOL while scanning string literal (Temp/ipykernel_54004/3019724405.py, line 261)